version: '3.4'

services:
  todo-app-api:
    container_name: todo-app-api
    build:
      context: ./TODO.WebApi
      dockerfile: Dockerfile
    ports:
      - "8980:80"
    networks:
      - mynetwork

  todoappsqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: todoappsqlserver
    ports:
      - "14330:1433"  
    environment:
      - SA_PASSWORD=Abc.123456
      - ACCEPT_EULA=Y
    networks:
      - mynetwork  

networks:
  mynetwork:
    driver: bridge

